/**
 * @delegolabs/api-generated
 *
 * Auto-generated TypeScript types from the Delego gateway OpenAPI spec (#633).
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY.
 *
 * Regenerate with:
 *   pnpm --filter @delegolabs/api-generated generate
 *
 * This file was generated from packages/api-generated/openapi.yaml.
 * Spec hash: 81e1277feba133f4
 * Generated at: 2026-08-25T21:13:20.489Z
 */

// ---------------------------------------------------------------------------
// Primitive types
// ---------------------------------------------------------------------------

/** Stroops represented as a string to survive JSON serialisation of BigInt. */
export type Stroops = string;

// ---------------------------------------------------------------------------
// Enumerations
// ---------------------------------------------------------------------------

export type OrderStatus =
  | "draft"
  | "pending_approval"
  | "approved"
  | "escrowed"
  | "fulfilled"
  | "settled"
  | "cancelled";

/** Structured reason recorded when a pending order is rejected (#567). */
export type RejectionReasonCode =
  | "too_expensive"
  | "wrong_item"
  | "wrong_merchant"
  | "wrong_time"
  | "other";

// ---------------------------------------------------------------------------
// Domain models
// ---------------------------------------------------------------------------

export interface LineItem {
  productId: string;
  quantity: number;
  /** Stroops as string-encoded bigint */
  unitPriceStroops: Stroops;
}

export interface Order {
  id: string;
  userId: string;
  delegationId: string;
  merchantId: string;
  status: OrderStatus;
  /** Stroops as string-encoded bigint */
  totalStroops: Stroops;
  lineItems: LineItem[];
  escrowContractId: string | null;
  rejectionReason?: RejectionReasonCode | null;
  /** Free-text detail accompanying rejectionReason (#567). */
  rejectionNote?: string | null;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Envelope
// ---------------------------------------------------------------------------

export interface ErrorBody {
  code: string;
  message: string;
}

export interface ApiResponse<T> {
  data: T | null;
  error: ErrorBody | null;
}

// ---------------------------------------------------------------------------
// Request / response shapes (approvals module)
// ---------------------------------------------------------------------------

/** GET /orders */
export type ListOrdersResponse = ApiResponse<Order[]>;

/** POST /orders/{id}/approve */
export interface ApproveOrderRequest {
  // intentionally empty — reserved for future fields
}

/** POST /orders/{id}/approve response */
export type ApproveOrderResponse = ApiResponse<Order>;

/** POST /orders/{id}/reject */
export interface RejectOrderRequest {
  rejectionReason?: RejectionReasonCode | null;
  rejectionNote?: string | null;
}

/** POST /orders/{id}/reject response */
export type RejectOrderResponse = ApiResponse<Order>;

// ---------------------------------------------------------------------------
// Adapter helpers
// ---------------------------------------------------------------------------
//
// The generated `Order` uses string dates and string-encoded bigint stroops.
// The existing @delegolabs/types `Order` uses `Date` and `bigint` natively.
// The adapter functions below are the seam between the generated API layer
// and the existing application models so consumers don't need to know about
// the serialisation difference.
//
// When @delegolabs/types is updated to match the API shapes, these adapters
// can be removed and call sites can consume the generated types directly.

import type { Order as DomainOrder, OrderStatus as DomainOrderStatus } from "@delegolabs/types";

function parseStroops(value: Stroops | undefined | null): bigint {
  if (value == null) return 0n;
  return BigInt(value);
}

/**
 * Maps a generated API `Order` (string dates, string stroops) to the
 * application domain `Order` (Date, bigint).
 */
export function adaptOrder(raw: Order): DomainOrder {
  return {
    id: raw.id,
    userId: raw.userId,
    delegationId: raw.delegationId,
    merchantId: raw.merchantId,
    status: raw.status as DomainOrderStatus,
    totalStroops: parseStroops(raw.totalStroops),
    lineItems: raw.lineItems.map((li) => ({
      productId: li.productId,
      quantity: li.quantity,
      unitPriceStroops: parseStroops(li.unitPriceStroops),
    })),
    escrowContractId: raw.escrowContractId,
    rejectionReason: raw.rejectionReason,
    rejectionNote: raw.rejectionNote,
    createdAt: new Date(raw.createdAt),
    updatedAt: new Date(raw.updatedAt),
  };
}

/**
 * Maps an array of generated API orders to domain orders.
 */
export function adaptOrders(raw: Order[]): DomainOrder[] {
  return raw.map(adaptOrder);
}
